//! PMTiles v3 archive output.
//!
//! The archive is written to a temporary file next to the destination and
//! renamed into place by [`PmTilesArchive::finalize`], so a crash or error
//! never leaves a truncated archive at the destination path. Tiles must be
//! added in strictly increasing tile-id (Hilbert) order, which yields a
//! clustered archive with run-length–encoded duplicates.

use std::collections::BTreeMap;
use std::fs::File;
use std::path::{Path, PathBuf};

use pmtiles::{Compression, PmTilesStreamWriter, PmTilesWriter, TileId, TileType};
use tracing::info;

use osmic_core::{BBox, TileCoord};

use crate::assemble::TileCompression;
use crate::encode::TileFormat;
use crate::error::TileError;

/// What one layer contains, collected while rendering.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct LayerStats {
    pub min_zoom: u8,
    pub max_zoom: u8,
    pub features: u64,
    /// Attribute keys seen on the layer's features.
    pub fields: std::collections::BTreeSet<String>,
}

impl LayerStats {
    /// Count one feature piece at `zoom`.
    pub fn record_piece(&mut self, zoom: u8) {
        if self.features == 0 {
            self.min_zoom = zoom;
            self.max_zoom = zoom;
        } else {
            self.min_zoom = self.min_zoom.min(zoom);
            self.max_zoom = self.max_zoom.max(zoom);
        }
        self.features += 1;
    }

    /// Note attribute keys seen on the layer. All pieces of a feature share
    /// its keys, so call this once per feature.
    pub fn record_fields(&mut self, fields: impl IntoIterator<Item = impl AsRef<str>>) {
        for f in fields {
            if !self.fields.contains(f.as_ref()) {
                self.fields.insert(f.as_ref().to_string());
            }
        }
    }

    pub fn merge(&mut self, other: &LayerStats) {
        if other.features == 0 {
            return;
        }
        if self.features == 0 {
            *self = other.clone();
            return;
        }
        self.min_zoom = self.min_zoom.min(other.min_zoom);
        self.max_zoom = self.max_zoom.max(other.max_zoom);
        self.features += other.features;
        self.fields.extend(other.fields.iter().cloned());
    }
}

/// Descriptive metadata for an archive.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ArchiveInfo {
    pub name: String,
    pub description: String,
    pub attribution: String,
}

impl Default for ArchiveInfo {
    fn default() -> Self {
        Self {
            name: "osmic".into(),
            description: "Vector tiles generated by osmic from OpenStreetMap data".into(),
            attribution: r#"<a href="https://www.openstreetmap.org/copyright" target="_blank">&copy; OpenStreetMap contributors</a>"#.into(),
        }
    }
}

/// TileJSON-style metadata JSON describing the layers actually present.
pub fn metadata_json(
    info: &ArchiveInfo,
    format: TileFormat,
    layers: &BTreeMap<String, LayerStats>,
) -> serde_json::Value {
    let vector_layers: Vec<serde_json::Value> = layers
        .iter()
        .filter(|(_, s)| s.features > 0)
        .map(|(id, s)| {
            let fields: serde_json::Map<String, serde_json::Value> = s
                .fields
                .iter()
                .map(|k| (k.clone(), serde_json::Value::from("String")))
                .collect();
            serde_json::json!({
                "id": id,
                "fields": fields,
                "minzoom": s.min_zoom,
                "maxzoom": s.max_zoom,
            })
        })
        .collect();
    serde_json::json!({
        "name": info.name,
        "description": info.description,
        "attribution": info.attribution,
        "type": "baselayer",
        "format": format.metadata_format(),
        "generator": concat!("osmic ", env!("CARGO_PKG_VERSION")),
        "vector_layers": vector_layers,
    })
}

/// Header settings for a new archive.
///
/// Create with [`ArchiveOptions::new`] and set the fields to change; new
/// fields may be added in minor releases.
#[derive(Debug, Clone)]
#[non_exhaustive]
pub struct ArchiveOptions {
    /// Format of the tiles.
    pub format: TileFormat,
    /// Compression the tiles were written with.
    pub compression: TileCompression,
    /// Geographic bounds of the data.
    pub bounds: BBox,
    /// Lowest zoom level with tiles.
    pub min_zoom: u8,
    /// Highest zoom level with tiles.
    pub max_zoom: u8,
    /// JSON metadata (TileJSON-style; see [`metadata_json`]).
    pub metadata: serde_json::Value,
    /// Replace an existing file at the destination (atomically).
    pub overwrite: bool,
}

impl ArchiveOptions {
    /// Options for `format` tiles at zoom levels `min_zoom..=max_zoom`:
    /// gzip-compressed, world bounds, empty metadata, and no overwriting of
    /// an existing file.
    pub fn new(format: TileFormat, min_zoom: u8, max_zoom: u8) -> Self {
        Self {
            format,
            compression: TileCompression::default(),
            bounds: BBox::world(),
            min_zoom,
            max_zoom,
            metadata: serde_json::json!({}),
            overwrite: false,
        }
    }
}

/// A PMTiles archive being written.
pub struct PmTilesArchive {
    writer: PmTilesStreamWriter<File>,
    temp: tempfile::NamedTempFile,
    path: PathBuf,
    overwrite: bool,
    last_tile_id: Option<u64>,
    tiles: u64,
}

fn archive_err(e: impl std::fmt::Display) -> TileError {
    TileError::Archive(e.to_string())
}

impl PmTilesArchive {
    /// Start an archive that will be renamed to `path` on finalize.
    pub fn create(path: &Path, options: &ArchiveOptions) -> Result<Self, TileError> {
        if !options.overwrite && path.exists() {
            return Err(TileError::Archive(format!(
                "{} already exists (refusing to overwrite)",
                path.display()
            )));
        }
        let temp = osmic_core::fs::temp_file_for(path)?;
        let file = temp.reopen()?;
        let tile_type = match options.format {
            TileFormat::Mvt => TileType::Mvt,
            TileFormat::Mlt => TileType::Mlt,
        };
        let tile_compression = match options.compression {
            TileCompression::Gzip => Compression::Gzip,
            TileCompression::None => Compression::None,
        };
        let b = options.bounds;
        let center = b.center();
        let writer = PmTilesWriter::new(tile_type)
            .tile_compression(tile_compression)
            .internal_compression(Compression::Gzip)
            .min_zoom(options.min_zoom)
            .max_zoom(options.max_zoom)
            .bounds(b.min_lon, b.min_lat, b.max_lon, b.max_lat)
            .center(center.lon, center.lat)
            .center_zoom(options.min_zoom.midpoint(options.max_zoom))
            .metadata(&options.metadata.to_string())
            .create(file)
            .map_err(archive_err)?;
        info!(path = %path.display(), "Writing PMTiles archive");
        Ok(Self {
            writer,
            temp,
            path: path.to_path_buf(),
            overwrite: options.overwrite,
            last_tile_id: None,
            tiles: 0,
        })
    }

    /// Add an already-compressed tile. Tiles must arrive in strictly
    /// increasing tile-id order.
    pub fn add_tile(&mut self, coord: TileCoord, data: &[u8]) -> Result<(), TileError> {
        let pm = pmtiles::TileCoord::new(coord.z.get(), coord.x, coord.y).map_err(archive_err)?;
        let id = TileId::from(pm).value();
        if self.last_tile_id.is_some_and(|last| id <= last) {
            return Err(TileError::Archive(format!(
                "tile {coord} added out of order (archive must stay clustered)"
            )));
        }
        self.last_tile_id = Some(id);
        self.writer.add_raw_tile(pm, data).map_err(archive_err)?;
        self.tiles += 1;
        Ok(())
    }

    /// Number of tiles added.
    pub fn tile_count(&self) -> u64 {
        self.tiles
    }

    /// Write directories and header, flush to disk, and atomically move the
    /// archive to its destination.
    pub fn finalize(self) -> Result<PathBuf, TileError> {
        self.writer.finalize().map_err(archive_err)?;
        let path = self.path;
        osmic_core::fs::persist(self.temp, &path, self.overwrite)?;
        info!(path = %path.display(), tiles = self.tiles, "PMTiles archive written");
        Ok(path)
    }
}

/// Hilbert tile id used to order an archive.
pub fn tile_id(coord: TileCoord) -> Result<u64, TileError> {
    let pm = pmtiles::TileCoord::new(coord.z.get(), coord.x, coord.y).map_err(archive_err)?;
    Ok(TileId::from(pm).value())
}

/// Inverse of [`tile_id`].
pub fn tile_coord(id: u64) -> Result<TileCoord, TileError> {
    let pm = pmtiles::TileCoord::from(TileId::new(id).map_err(archive_err)?);
    let z = osmic_core::Zoom::try_from(pm.z()).map_err(archive_err)?;
    Ok(TileCoord::new(pm.x(), pm.y(), z))
}

#[cfg(test)]
mod tests {
    use super::*;
    use osmic_core::Zoom;

    fn options(overwrite: bool) -> ArchiveOptions {
        let mut options = ArchiveOptions::new(TileFormat::Mvt, 0, 1);
        assert_eq!(options.compression, TileCompression::Gzip);
        assert!(!options.overwrite, "never overwrite unless asked");
        options.compression = TileCompression::None;
        options.bounds = BBox::new(-1.0, -1.0, 1.0, 1.0);
        options.metadata = serde_json::json!({"name": "t"});
        options.overwrite = overwrite;
        options
    }

    #[test]
    fn tile_id_round_trip_and_order() {
        let a = TileCoord::new(0, 0, Zoom::clamped(0));
        let b = TileCoord::new(1, 1, Zoom::clamped(1));
        assert!(tile_id(a).expect("valid") < tile_id(b).expect("valid"));
        assert_eq!(tile_coord(tile_id(b).expect("valid")).expect("valid"), b);
        // Valid in PMTiles (up to z31) but beyond the supported zoom range.
        let z23 = pmtiles::TileCoord::new(23, 0, 0).expect("valid in PMTiles");
        assert!(tile_coord(TileId::from(z23).value()).is_err());
    }

    #[test]
    fn out_of_order_tiles_are_rejected_and_nothing_is_left_behind() {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("out.pmtiles");
        let mut a = PmTilesArchive::create(&path, &options(false)).expect("create");
        a.add_tile(TileCoord::new(1, 1, Zoom::clamped(1)), b"x")
            .expect("first");
        assert!(
            a.add_tile(TileCoord::new(0, 0, Zoom::clamped(0)), b"y")
                .is_err()
        );
        drop(a);
        assert!(!path.exists(), "no partial archive at the destination");
        assert_eq!(
            std::fs::read_dir(dir.path()).expect("read").count(),
            0,
            "temp removed"
        );
    }

    #[test]
    fn finalize_persists_and_respects_overwrite() {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("out.pmtiles");
        let mut a = PmTilesArchive::create(&path, &options(false)).expect("create");
        a.add_tile(TileCoord::new(0, 0, Zoom::clamped(0)), b"tile")
            .expect("add");
        a.finalize().expect("finalize");
        assert!(path.exists());
        assert!(PmTilesArchive::create(&path, &options(false)).is_err());
        let b = PmTilesArchive::create(&path, &options(true)).expect("overwrite allowed");
        b.finalize().expect("finalize");
    }

    #[test]
    fn metadata_lists_only_present_layers() {
        let mut layers = BTreeMap::new();
        let mut roads = LayerStats::default();
        roads.record_piece(5);
        roads.record_fields(["class", "name"]);
        roads.record_piece(9);
        roads.record_fields(["class", "ref"]);
        layers.insert("highway".to_string(), roads);
        layers.insert("shop".to_string(), LayerStats::default());
        let m = metadata_json(&ArchiveInfo::default(), TileFormat::Mvt, &layers);
        let vl = m["vector_layers"].as_array().expect("array");
        assert_eq!(vl.len(), 1);
        assert_eq!(vl[0]["id"], "highway");
        assert_eq!(vl[0]["minzoom"], 5);
        assert_eq!(vl[0]["maxzoom"], 9);
        assert_eq!(vl[0]["fields"].as_object().expect("obj").len(), 3);
        assert!(
            m["attribution"]
                .as_str()
                .expect("str")
                .contains("OpenStreetMap")
        );
    }
}
