[package]
name = "osmic-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
categories = ["science::geo", "rust-patterns"]
keywords = ["plugin", "app", "framework", "map"]
readme.workspace = true
description = "Application framework for osmic: plugins, typed resources, events and a runner"

[dependencies]
thiserror = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
