[package]
name = "osmic-text"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
categories = ["text-processing", "graphics"]
keywords = ["text-shaping", "labels", "collision", "cosmic-text"]
readme.workspace = true
description = "Text shaping, deterministic label placement with collision detection and line-following labels, glyph rasterisation and premultiplied compositing"

[dependencies]
osmic-core = { workspace = true }
cosmic-text = { workspace = true }
rstar = { workspace = true }

[lints]
workspace = true
